#ifndef RTE_APPLICATION2_SWC_LEDSWITCHING_H_
#define RTE_APPLICATION2_SWC_LEDSWITCHING_H_


#include "Rte.h"


extern void Dio_WriteChannel_Runnable(Port_NumID* CS_2_WriteChannel_Operation_1_Argument_1_PortNum,Dio_ChannelType* CS_2_WriteChannel_Operation_1_Argument_2_ChannelType,Dio_LevelType* CS_2_WriteChannel_Operation_1_Argument_3_LevelType);


#define    Rte_Call_R_Port_3_CS_2_LedState_CS_2_WriteChannel_Operation_1(CS_2_WriteChannel_Operation_1_Argument_1_PortNum,CS_2_WriteChannel_Operation_1_Argument_2_ChannelType,CS_2_WriteChannel_Operation_1_Argument_3_LevelType)     (Dio_WriteChannel_Runnable(CS_2_WriteChannel_Operation_1_Argument_1_PortNum,CS_2_WriteChannel_Operation_1_Argument_2_ChannelType,CS_2_WriteChannel_Operation_1_Argument_3_LevelType))
#define    Rte_Read_R_Port_1_SR1_Button1State_SR_1_Button1State_Element_1(data)     (Rte_Read_TopLevelComposition_Prototype_2_R_Port_1_SR1_Button1State_SR_1_Button1State_Element_1(data))
#define    Rte_Read_R_Port_2_SR2_Button2State_SR_2_Button2State_Element_1(data)     (Rte_Read_TopLevelComposition_Prototype_2_R_Port_2_SR2_Button2State_SR_2_Button2State_Element_1(data))



#endif
